import React from 'react';
import Head from 'next/head'
import styles from './index.module.scss'
import Welcome from "@/components/Welcome/Welcome";
export default function HomePage() {
  return (
    <>
      <Head>
        <title>Home | WishLister</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Welcome></Welcome>
      </main>
    </>
  )
}
